services:
  # Prowlarr Service
  prowlarr:
    image: binhex/arch-prowlarr
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/binhex-prowlarr:/config
    ports:
      - 9696:9696
    environment:
      - TZ=America/New_York
    networks:
      - proxy

  # Radarr Service
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/radarr:/config
      - /mnt/user:/data
    ports:
      - 7878:7878
    environment:
      - TZ=America/New_York
    networks:
      - proxy

  # Sonarr Service
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/sonarr:/config
      - /mnt/user:/data
    ports:
      - 8989:8989
    environment:
      - TZ=America/New_York
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
    networks:
      - proxy

  # Watchlistarr Service
  watchlistarr:
    image: nylonee/watchlistarr:latest
    container_name: watchlistarr
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/watchlistarr:/config  # Config and data location
      - /mnt/user/downloads:/downloads         # Downloads location
    environment:
      - TZ=America/New_York  # Set your timezone
      - RADARR_BASE_URL=http://192.168.1.2:7878
      - RADARR_API_KEY=c1b4e22974964c9cbd100db651b53777
      - SONARR_BASE_URL=http://192.168.1.2:8989
      - PLEX_TOKEN=6i3eQ4-ovfhuX9FGsgg7
      - SONARR_API_KEY=c6bdc461a76949f1940c714ae54603e2
      - REFRESH_INTERVAL_SECONDS=60  # Sync interval in seconds
    networks:
      - proxy

  # Overseerr Service
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/overseerr:/config
    ports:
      - 5055:5055
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
      - PLEX_TOKEN=6i3eQ4-ovfhuX9FGsgg7
    networks:
      - proxy

  # Unpackerr Service
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/unpackerr:/config
      - /mnt/user/downloads:/downloads
    ports:
      - 9915:9915
    environment:
      - TZ=America/New_York
      - UNPACKERR_INTERVAL=60
    networks:
      - proxy

  # Tautulli Service
  tautulli:
    image: ghcr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/tautulli:/config
    ports:
      - 8181:8181
    environment:
      - TZ=America/New_York
      - PLEX_URL=http://192.168.1.2:32400
      - PLEX_TOKEN=6i3eQ4-ovfhuX9FGsgg7
    networks:
      - proxy

networks:
  proxy:
    external: true  # Use an existing proxy network for communication between services
