version: '3.7'

services:
  # Prowlarr Service
  prowlarr:
    image: binhex/arch-prowlarr
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/binhex-prowlarr:/config
    ports:
      - 9696:9696
    environment:
      - TZ=America/New_York
    networks:
      - proxy

  # Radarr Service
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/radarr:/config
      - /mnt/user:/data
    ports:
      - 7878:7878
    environment:
      - TZ=America/New_York
    networks:
      - proxy

  # Sonarr Service
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/sonarr:/config
      - /mnt/user:/data
    ports:
      - 8989:8989
    environment:
      - TZ=America/New_York
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
    networks:
      - proxy

  # Watchlistarr Service
  watchlistarr:
    image: nylonee/watchlistarr:latest
    container_name: watchlistarr
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/watchlistarr:/config  # Config and data location
      - /mnt/user/downloads:/downloads         # Downloads location
    ports:
      - 8181:8181  # Expose the web UI on port 8181
      - 3748:3748  # Dummy Port for Service Monitoring
    environment:
      - TZ=America/New_York  # Set your timezone
      - RADARR_BASE_URL=http://192.168.1.2:7878
      - RADARR_API_KEY=c1b4e22974964c9cbd100db651b53777
      - SONARR_BASE_URL=http://192.168.1.2:8989
      - PLEX_TOKEN=6i3eQ4-ovfhuX9FGsgg7
      - SONARR_API_KEY=c6bdc461a76949f1940c714ae54603e2
      - REFRESH_INTERVAL_SECONDS=60  # Sync interval in seconds
    networks:
      - proxy

networks:
  proxy:
    external: true  # Use an existing proxy network for communication between services
