services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/homeassistant:/config  # Replace with your desired config path
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York  # Set your timezone
    ports:
      - 8123:8123  # Home Assistant Web UI
    network_mode: host  # Use host networking for device discovery (recommended for Home Assistant)

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/MQTT:/mosquitto/config
      - /mnt/secondary-cache/appdata/MQTT/data:/mosquitto/data
      - /mnt/secondary-cache/appdata/MQTT/log:/mosquitto/log
    environment:
      - TZ=America/New_York
    ports:
      - 1883:1883  # MQTT Port
      - 9001:9001  # WebSocket Port
