services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/overseerr:/config
    ports:
      - 5055:5055
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
      - PLEX_TOKEN=6i3eQ4-ovfhuX9FGsgg7
    networks:
      - proxy

networks:
  proxy:
    external: true
