services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/tautulli:/config
    ports:
      - 8181:8181
    environment:
      - TZ=America/New_York
      - PLEX_URL=http://192.168.1.2:32400
      - PLEX_TOKEN=6i3eQ4-ovfhuX9FGsgg7
    networks:
      - proxy

networks:
  proxy:
    external: true
