services:
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/unpackerr:/config
      - /mnt/user/downloads:/downloads
    ports:
      - 9915:9915
    environment:
      - TZ=America/New_York
      - UNPACKERR_INTERVAL=60
    networks:
      - proxy

networks:
  proxy:
    external: true
