services:
  # pgAdmin 4 - PostgreSQL management
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/pgadmin4:/var/lib/pgadmin
    ports:
      - 8792:80  # Web UI port
    environment:
      - PGADMIN_DEFAULT_EMAIL=ech0@mailfence.com  # Set admin email
      - PGADMIN_DEFAULT_PASSWORD=pg-aPAib5007  # Set admin password
      - TZ=America/New_York

  # Adminer - Database management tool
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - 6062:8080  # Web UI port
    environment:
      - TZ=America/New_York

  # phpMyAdmin - MySQL/MariaDB management
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8023:80  # Web UI port
    environment:
      - PMA_HOST=192.168.1.2  # Set database host
      - PMA_PORT=3307         # Set database port
      - TZ=America/New_York

  # DB Backup - Postgres 12.5
  db-backup-postgres12:
    image: tiredofit/db-backup:latest
    container_name: db-backup-postgres12
    restart: unless-stopped
    volumes:
      - /mnt/user/backup/db-backup/postgres125:/backup
    environment:
      - DEFAULT_COMPRESSION_LEVEL=GZ
      - DB_TYPE=pgsql
      - DB_HOST=192.168.1.2
      - DB_NAME=ALL
      - DB_USER=root
      - DB_PASS=unraid-aPAib5007
      - DB_PORT=5432
      - DEFAULT_BACKUP_INTERVAL=1440
      - DEFAULT_BACKUP_BEGIN=0302
      - DEFAULT_CLEANUP_TIME=87600
      - DEFAULT_ENABLE_PARALLEL_COMPRESSION=TRUE
      - MD5=TRUE
      - DEFAULT_SPLIT_DB=FALSE
      - TZ=America/New_York

  # DB Backup - Postgres 14
  db-backup-postgres14:
    image: tiredofit/db-backup:latest
    container_name: db-backup-postgres14
    restart: unless-stopped
    volumes:
      - /mnt/user/backup/db-backup/postgres14:/backup
    environment:
      - DEFAULT_COMPRESSION_LEVEL=GZ
      - DB_TYPE=pgsql
      - DB_HOST=192.168.1.2
      - DB_NAME=ALL
      - DB_USER=root
      - DB_PASS=unraid-aPAib5007
      - DB_PORT=5433
      - DEFAULT_BACKUP_INTERVAL=1440
      - DEFAULT_BACKUP_BEGIN=0302
      - DEFAULT_CLEANUP_TIME=87600
      - DEFAULT_ENABLE_PARALLEL_COMPRESSION=TRUE
      - MD5=TRUE
      - DEFAULT_SPLIT_DB=FALSE
      - TZ=America/New_York

  # DB Backup - Postgres 15
  db-backup-postgres15:
    image: tiredofit/db-backup:latest
    container_name: db-backup-postgres15
    restart: unless-stopped
    volumes:
      - /mnt/user/backup/db-backup/postgres15:/backup
    environment:
      - DEFAULT_COMPRESSION_LEVEL=GZ
      - DB_TYPE=pgsql
      - DB_HOST=192.168.1.2
      - DB_NAME=ALL
      - DB_USER=root
      - DB_PASS=unraid-aPAib5007
      - DB_PORT=5434
      - DEFAULT_BACKUP_INTERVAL=1440
      - DEFAULT_BACKUP_BEGIN=0302
      - DEFAULT_CLEANUP_TIME=87600
      - DEFAULT_ENABLE_PARALLEL_COMPRESSION=TRUE
      - MD5=TRUE
      - DEFAULT_SPLIT_DB=FALSE
      - TZ=America/New_York

  # DB Backup - MariaDB
  db-backup-mariadb:
    image: tiredofit/db-backup:latest
    container_name: db-backup-mariadb
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/db-backup/mariadb:/backup
    environment:
      - DEFAULT_COMPRESSION_LEVEL=GZ
      - DB_TYPE=mysql
      - DB_HOST=192.168.1.2
      - DB_NAME=ALL
      - DB_USER=root
      - DB_PASS=unraid-aPAib5007
      - DB_PORT=3306
      - DEFAULT_BACKUP_INTERVAL=1440
      - DEFAULT_BACKUP_BEGIN=0315
      - DEFAULT_CLEANUP_TIME=87600
      - DEFAULT_ENABLE_PARALLEL_COMPRESSION=TRUE
      - MD5=TRUE
      - DEFAULT_SPLIT_DB=FALSE
      - TZ=America/New_York

networks:
  default:
    external: false
