version: '3.7'

services:
  prowlarr:
    image: binhex/arch-prowlarr
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/binhex-prowlarr:/config
    ports:
      - 9696:9696
    environment:
      - TZ=America/New_York
    networks:
      - proxy

networks:
  proxy:
    external: true
