version: '3.7'

services:
  radarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - /mnt/secondary-cache/appdata/sonarr:/config
      - /mnt/user:/data
    ports:
      - 8989:8989
    environment:
      - TZ=America/New_York
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
    networks:
      - proxy

networks:
  proxy:
    external: true
